version: "3.3"

services:
  sandbox-go:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        - SANDBOX_USER_UID=999
        - SANDBOX_DIR=/sandbox
    image: sandbox-go
    container_name: sandbox-go
    volumes:
      - ../src:/app/src
      - import:/sandbox/import:ro
    ports:
      - "9010:9010"
    environment:
      - SANDBOX_USER_UID=999
      - SANDBOX_DIR=/sandbox
    restart: on-failure
    command: gunicorn --pythonpath '/app' --bind 0:9010 src.app.main:app --reload -w 1

    networks:
      - localhost

networks:
  localhost:
    external: true

volumes:
  import:
    external: true
